### ISSUE TITLE
Any interest in supporting procs?

### ISSUE THREAD

**Issue by samstickland** [etiennebarrie/kwattr#2]
For example:

`kwattr now: -> { Time.current }`

I can put together a PR.

**Comment by etiennebarrie** [comment]
I don't want to because I don't want to prevent people from having proc default values if they want to.
e.g.

```ruby
class TakesAProc
  kwattr now: -> { Time.current}

  def call_now
    @now.call
  end
end
```

If you want default values, you can define `initialize` and at least you don't have to deal with calling `super` since the provided initialize is prepended.

```ruby
class Example
  kwattr foo: 42

  def initialize(now: Time.now)
    @now = now
  end

  def to_s
    "#@foo #@now"
  end
end
```

```ruby
> puts Example.new
42 2017-05-26 17:14:44 -0400
=> nil
> puts Example.new
42 2017-05-26 17:14:52 -0400
```

Maybe we could add something to the README, not sure.
